/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practico.pkg6.vistas;

import javax.swing.JOptionPane;
import practico.pkg6.clases.Listas;

/**
 *
 * @author luciano.echevarne
 */
public class BuscarCliente extends javax.swing.JInternalFrame {
    
    /**
     * Creates new form BuscarCliente
     */
    public BuscarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ttelefono = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Blimpiarformulario = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Tapellido = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Tciudad = new javax.swing.JTextField();
        BbusquedaPtelefono = new javax.swing.JButton();
        BbusquedaPciudad = new javax.swing.JButton();
        BbusquedaPapellido = new javax.swing.JButton();

        setClosable(true);

        jLabel3.setText("Apellido:");

        Blimpiarformulario.setText("Limpiar");
        Blimpiarformulario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlimpiarformularioActionPerformed(evt);
            }
        });

        jLabel5.setText("Ciudad:");

        jLabel6.setText("Telefono:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Busqueda de cliente");

        BbusquedaPtelefono.setText("Buscar");
        BbusquedaPtelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BbusquedaPtelefonoActionPerformed(evt);
            }
        });

        BbusquedaPciudad.setText("Buscar");
        BbusquedaPciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BbusquedaPciudadActionPerformed(evt);
            }
        });

        BbusquedaPapellido.setText("Buscar");
        BbusquedaPapellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BbusquedaPapellidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Blimpiarformulario)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Tapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BbusquedaPapellido))))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Ttelefono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                            .addComponent(Tciudad, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BbusquedaPtelefono)
                            .addComponent(BbusquedaPciudad))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BbusquedaPapellido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BbusquedaPciudad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BbusquedaPtelefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(Blimpiarformulario)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BbusquedaPtelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BbusquedaPtelefonoActionPerformed
        long telefono=0;
        try{    
        telefono=Integer.parseInt(Ttelefono.getText());}
        catch(NumberFormatException ex){
        JOptionPane.showMessageDialog(this,"Volver a cargar, en campo telefono ingresar solo numeros");
        }
        Tapellido.setText("");
        Tciudad.setText("");
        Ttelefono.setText("");
        Listas l1=new Listas();
        if(l1.buscarCliente(telefono)==null){JOptionPane.showMessageDialog(this,"No se encontraron datos");}
        else
        JOptionPane.showMessageDialog(this,l1.buscarCliente(telefono));
        //System.out.println(l1.buscarCliente(telefono));
        // TODO add your handling code here:
    }//GEN-LAST:event_BbusquedaPtelefonoActionPerformed

    private void BbusquedaPapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BbusquedaPapellidoActionPerformed
        String apellido=Tapellido.getText();
        Tapellido.setText("");
        Tciudad.setText("");
        Ttelefono.setText("");
        Listas l1=new Listas();
        if(l1.buscarTelefono(apellido).isEmpty()){JOptionPane.showMessageDialog(this,"El cliente no esta cargado");}
        else
        JOptionPane.showMessageDialog(this,"Telefono: "+l1.buscarTelefono(apellido));
    // TODO add your handling code here:
    }//GEN-LAST:event_BbusquedaPapellidoActionPerformed

    private void BbusquedaPciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BbusquedaPciudadActionPerformed
        String ciudad=Tciudad.getText();
        Tapellido.setText("");
        Tciudad.setText("");
        Ttelefono.setText("");
        Listas l1=new Listas();
        if(l1.buscarClientes(ciudad).isEmpty()){JOptionPane.showMessageDialog(this,"No se encontraron datos");}
        else
        JOptionPane.showMessageDialog(this,l1.buscarClientes(ciudad));


        // TODO add your handling code here:
    }//GEN-LAST:event_BbusquedaPciudadActionPerformed

    private void BlimpiarformularioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlimpiarformularioActionPerformed

    Tapellido.setText("");
    Tciudad.setText("");
    Ttelefono.setText("");  
// TODO add your handling code here:
    }//GEN-LAST:event_BlimpiarformularioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BbusquedaPapellido;
    private javax.swing.JButton BbusquedaPciudad;
    private javax.swing.JButton BbusquedaPtelefono;
    private javax.swing.JButton Blimpiarformulario;
    private javax.swing.JTextField Tapellido;
    private javax.swing.JTextField Tciudad;
    private javax.swing.JTextField Ttelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
